//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGCP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSGCPAEntities1 : DbContext
    {
        public MSGCPAEntities1()
            : base("name=MSGCPAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Examination> Examination { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Remark> Remark { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<ResultTotal> ResultTotal { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<SubjectMarks> SubjectMarks { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
