//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGCP
{
    using System;
    using System.Collections.Generic;
    public partial class ResultTotal
    {
        public int ResultTotal_Id { get; set; }
        public Nullable<int> obtained_Total { get; set; }
        public string examination_Type { get; set; }
        public Nullable<int> full_Total { get; set; }
        public Nullable<int> pass_Total { get; set; }
        public Nullable<double> percentage { get; set; }
        public string division { get; set; }
        public string student_Name { get; set; }
        public string grade { get; set; }
        public string section { get; set; }
        public string roll_No { get; set; }
        public Nullable<int> result_Id { get; set; }
        public virtual Result Result { get; set; }
    }
}
