//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGCP
{
    using System;
    using System.Collections.Generic;
    using System.Security.Cryptography;
    using System.Text;
    public partial class User
    {
        MSGCPAEntities1 db = new MSGCPAEntities1();
        static string Encrypt(string value)
        {
            using (MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider())
            {
                UTF8Encoding utf8 = new UTF8Encoding();
                byte[] data = md5.ComputeHash(utf8.GetBytes(value));
                return Convert.ToBase64String(data);
            }
        }
        public int user_Id { get; set; }
        public string user_Name { get; set; }
        public string password { get; set; }

        public bool checkLogin(string uname, string pass)
        {
            foreach (var user in db.User)
            {
                if (user.user_Name==uname && Encrypt(pass)==user.password)
                {
                    return true;
                }
            }
            return false; 
        }
    }
}
